import type { Metadata } from 'next';
import './globals.css';
import theme from '@/styles/theme';
import {ThemeProvider} from '@mui/material/styles';
import {ProjectProvider} from '@/hooks/project/project-context';
import {Providers} from '@/app/api/auth/providers/Providers';
import SessionGuard from '@/components/SessionGuard/SessionGuard';
import React from 'react';
import { TableProvider } from '@/hooks/table/table-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ProjectProvider>
          <TableProvider>
            <Providers>
              <SessionGuard>
                <ThemeProvider theme={theme}>
                  {children}
                </ThemeProvider>
              </SessionGuard>
            </Providers>
          </TableProvider>
        </ProjectProvider>
      </body>
    </html>
  );
}

