import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import theme from '@/styles/theme';
import {ThemeProvider} from '@mui/material/styles';
import {ProjectProvider} from '@/hooks/project/project-context';
import {Providers} from '@/app/api/auth/providers/Providers';
import SessionGuard from '@/components/SessionGuard/SessionGuard';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProjectProvider>
          <Providers>
            <SessionGuard>
              <ThemeProvider theme={theme}>
                {children}
              </ThemeProvider>
            </SessionGuard>
          </Providers>
        </ProjectProvider>
      </body>
    </html>
  );
}

